name: Pylint
on: [push]
jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install build requirements of Python dependencies
        run: sudo apt-get update && sudo apt-get -y install libpq-dev libjpeg-dev libz-dev libldap2-dev libsasl2-dev

      - name: Ensure latest pip is installed
        run: python -m pip install --upgrade pip

      - name: Install NAV Python requirements
        run: pip install -r requirements.txt -r tests/requirements.txt

      - name: Run PyLint
        run: mkdir reports && tests/docker/scripts/pylint.sh python/nav --jobs=4 --rcfile=python/pylint.rc --disable=I,similarities --load-plugins pylint_django
